import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#111315",
    padding: 20,
    paddingBottom: 80, // leave space for navbar
  },
  header: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 20,
  },
  eventBox: {
    marginTop: 20,
    backgroundColor: "#1D2D44",
    padding: 15,
    borderRadius: 10,
  },
  eventTitle: {
    color: "#A6E1FA",
    fontSize: 16,
    marginBottom: 8,
    fontWeight: "600",
  },
  eventRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#2A3B5C",
    padding: 10,
    borderRadius: 6,
    marginBottom: 6,
  },
  eventText: {
    color: "#FFFFFF",
    fontSize: 14,
    flex: 1,
  },
  editText: {
    color: "#A6E1FA",
    fontSize: 14,
    marginHorizontal: 8,
    fontWeight: "600",
  },
  deleteText: {
    color: "red",
    fontSize: 14,
    fontWeight: "600",
  },
  noEvent: {
    marginTop: 20,
    color: "#A7A9AB",
    fontSize: 14,
    fontStyle: "italic",
  },
  addButton: {
    marginTop: 12,
    backgroundColor: "#A6E1FA",
    padding: 12,
    borderRadius: 6,
    alignItems: "center",
  },
  addButtonText: {
    color: "#111315",
    fontWeight: "700",
    fontSize: 14,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(17, 19, 21, 0.7)",
  },
  modalBox: {
    width: "80%",
    backgroundColor: "#24416B",
    padding: 20,
    borderRadius: 10,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#A6E1FA",
    marginBottom: 10,
    textAlign: "center",
  },
  input: {
    backgroundColor: "#111315",
    color: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#A7A9AB",
    borderRadius: 6,
    padding: 10,
    marginBottom: 15,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  addEventButton: {
    flex: 1,
    backgroundColor: "#A6E1FA",
    padding: 10,
    borderRadius: 6,
    marginRight: 5,
    alignItems: "center",
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "#444",
    padding: 10,
    borderRadius: 6,
    marginLeft: 5,
    alignItems: "center",
  },
  cancelButtonText: {
    color: "#FFF",
    fontWeight: "600",
  },
  navbar: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 15,
    borderTopWidth: 1,
    borderTopColor: "#333",
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#1D2D44",
  },
  navText: {
    color: "#A6E1FA",
    fontSize: 16,
  },
});
